service: iot-pkg-devices

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

package:
  exclude:
    - tmp/**
    - .git/**
    - .gitignore
    - .idea/**
    - data/**
    - script/**
    - template/**
    - package.json

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  stage: qa
  environment:
    DYNAMODB_TABLE: ${opt:stage, self:provider.stage}-${self:service}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  deleteDevice:
    handler: handler/device-delete.deleteDevice
    description: delete device
    events:
      - http:
          path: devices/{did}
          method: delete
          cors: true

  lookupDevice:
    handler: handler/device-lookup.lookupDevice
    description: lookup device
    events:
      - http:
          path: devices/{did}
          method: get
          cors: true

  createSensor:
    handler: handler/sensor-create.createSensor
    description: create device
    events:
      - http:
          path: sensor
          method: post
          cors: true

  deleteSensor:
    handler: handler/sensor-delete.deleteSensor
    description: delete sensor
    events:
      - http:
          path: sensor/{sid}
          method: delete
          cors: true

  lookupSensor:
    handler: handler/sensor-lookup.lookupSensor
    description: lookup sensor
    events:
      - http:
          path: sensor/{sid}
          method: get
          cors: true

  updateSensor:
    handler: handler/sensor-update.updateSensor
    description: update sensor
    events:
      - http:
          path: sensor/{sid}
          method: put
          cors: true

  deleteUser:
    handler: handler/user-delete.deleteUser
    description: delete user
    events:
      - http:
          path: user/{uid}
          method: delete
          cors: true

resources:
  Resources:
    devicesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: sid
            AttributeType: S
          -
            AttributeName: uid
            AttributeType: S
          -
            AttributeName: did
            AttributeType: S
        KeySchema:
          -
            AttributeName: sid
            KeyType: HASH
          -
            AttributeName: uid
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        LocalSecondaryIndexes:
          - IndexName: "sid-did-index"
            KeySchema:
              - AttributeName: "sid"
                KeyType: "HASH"
              - AttributeName: "did"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"

        GlobalSecondaryIndexes:
          - IndexName: "did-uid-index"
            KeySchema:
              - AttributeName: "did"
                KeyType: "HASH"
              - AttributeName: "uid"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
