service: iot-package-devices

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  stage: qa
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  createDevice:
    handler: handler/createDevice.createDevice
    events:
      - http:
          path: devices
          method: post
          cors: true

  lookupDevice:
    handler: handler/lookupDevice.lookupDevice
    events:
      - http:
          path: devices/{id}
          method: get
          cors: true

  get:
    handler: handler/get.get
    events:
      - http:
          path: devices/{id}
          method: get
          cors: true

  update:
    handler: handler/update.update
    events:
      - http:
          path: devices/{id}
          method: put
          cors: true

  delete:
    handler: handler/delete.delete
    events:
      - http:
          path: devices/{id}
          method: delete
          cors: true

resources:
  Resources:
    devicesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: deviceId
            AttributeType: S
          -
            AttributeName: sensorId
            AttributeType: S
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: deviceId
            KeyType: HASH
          -
            AttributeName: sensorId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
        - IndexName: "deviceId-userId-index"
          KeySchema:
          - AttributeName: "deviceId"
            KeyType: "HASH"
          - AttributeName: "userId"
            KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
